project: dot
providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: secrets
        path: projects/vfarcic
        keys:
          github-user: GITHUB_USER
          github-token: GITHUB_TOKEN
          port-client-id: PORT_CLIENT_ID
          port-client-secret: PORT_CLIENT_SECRET
