apiVersion: devopstoolkit.live/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    namespace: staging
    image: ghcr.io/vfarcic/idp-full-demo
    tag: 0.0.7
    port: 8080
    host: staging.silly-demo.34.118.251.24.nip.io
    ingressClassName: contour
    db:
      secret: silly-demo-db
      storeName: google
      name: main
