apiVersion: devopstoolkit.live/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
  labels:
    app-owner: vfarcic
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    namespace: a-team
    image: ghcr.io/vfarcic/silly-demo
    tag: 1.4.342
    port: FIXME
    host: silly-demo.135.237.72.117.nip.io
    ingressClassName: contour
    db:
      secret: silly-demo-db-20250101023513
    repository:
      enabled: true
      name: idp-full-app
    ci:
      enabled: true
