---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backstage-demo.fullname" . }}
  labels:
    {{- include "backstage-demo.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "backstage-demo.fullname" . }}
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
