apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
  namespace: default
spec:
  compositionRef:
    name: app-backend
  id: silly-demo
  parameters:
    db:
      secret: silly-demo-db
    host: silly-demo.127.0.0.1.nip.io
    image: ghcr.io/vfarcic/idp-full-demo:latest
    ingressClassName: nginx
    namespace: a-team
    port: 8080
    scaling:
      enabled: true
      max: 6
      min: 2
